M48
; DRILL file {KiCad 7.0.5-0} date 2023 July 31, Monday 21:43:22
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-31T21:43:22-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,Plated,1,4,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0433
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0630
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0866
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.1181
%
G90
G05
T1
X5.5079Y-4.0069
X5.5187Y-3.7037
X5.998Y-3.5276
X5.999Y-2.936
T2
X5.686Y-3.8051
T3
X4.8986Y-3.8051
T4
X5.2933Y-2.247
T5
X5.0177Y-4.2421
X5.9626Y-2.2736
X5.9626Y-4.2421
T0
M30
